### ISSUE TITLE
Break the link between GPS and flaps

### ISSUE THREAD

**Issue by DeepReset** [BitsAndDroids/BitsAndDroidsFlightSimLibrary#4]
case 454: {
            gpsCourseToSteer = cutValue.toInt();
        }

        // Flaps
        case 510: {
            flapsHandlePct = cutValue.toInt();
            break;
        }

This seems to be missing a "break"

**Comment by BitsAndDroids** [comment]
You are absolutely right! I'll fix it immediately.
