### ISSUE TITLE
SoftwareSerial - ESP32 Incompatibility, Hardware Serial required

### ISSUE THREAD

**Issue by ObscureCode** [BitsAndDroids/BitsAndDroidsFlightSimLibrary#7]
Hey, there Dave I just went to transition my project from an Arduino nano to an esp32 and have come across a Software serial issue. Which I found odd as it appears that in the library you had already thought about the hardware serial with the DUO. I was wondering if you would at all consider making this change for the esp series also as I see great advantages in using these boards.

I tried making the changes to the library as a test on my end by just adjusting the conditions at the top of the cpp and h but was out of my scope I am afraid. Thanks again for all you work on these modules/libraries and connecting software!

```
Arduino: 1.8.13 (Mac OS X), Board: "NodeMCU-32S, 80MHz, 921600, None, Disabled"

In file included from /Users/#redacted#/AccelStepper_29_esp32-transistion.ino:2:
/Users/elliott/Documents/Arduino/libraries/BitsAndDroidsFlightSimLibrary/BitsAndDroidsFlightConnector.h:9:10: fatal error: SoftwareSerial.h: No such file or directory
 #include <SoftwareSerial.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board NodeMCU-32S.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by BitsAndDroids** [comment]
Thanks for the heads-up. I mainly use ESP32 boards but haven't encountered this problem yet. I will do some testing and make the proper changes. Forgot that I usually use a fork without the library included for esp32's. But that isn't ideal to manage 2 libraries. Will add filters to the main library

**Comment by BitsAndDroids** [comment]
The latest library on here has checks and balances for esp based boards. The connector is currently building a release bundled with the latest library

**Comment by ObscureCode** [comment]
Amazing thank you very much!

**Comment by ObscureCode** [comment]
Maybe it's just me, but even with the newly updated library re-added to Arduino IDE, I still get the following error:


```
Arduino: 1.8.13 (Mac OS X), Board: "NodeMCU-32S, 80MHz, 921600, None, Disabled"

In file included from /Users/elliott/#redacted#/AccelStepper_29_esp32-transistion.ino:2:
/Users/elliott/Documents/Arduino/libraries/BitsAndDroidsFlightSimLibrary/BitsAndDroidsFlightConnector.h:9:10: fatal error: SoftwareSerial.h: No such file or directory
 #include "SoftwareSerial.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board NodeMCU-32S.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by ObscureCode** [comment]
[BitsAndDroidsFlightSimLibrary 2.zip](https://github.com/BitsAndDroids/BitsAndDroidsFlightSimLibrary/files/15457775/BitsAndDroidsFlightSimLibrary.2.zip)

That's the most up-to-date library I have added - directly from the connector.

**Comment by BitsAndDroids** [comment]
Hmmm... I hoped it would recognize the entire esp32 family but it seems the esp32s isn't recognized as esp. Will try more variants to verify and make changes accordingly

**Comment by BitsAndDroids** [comment]
Ah wait a sec, it seems the connector is still spitting out the old version somehow. Investigating atm

**Comment by BitsAndDroids** [comment]
Nope the fix was simple. I put the release notes at the wrong release and forgot to publish the latest. Found a small bug in the process. Release should be live in a few (v20)

**Comment by BitsAndDroids** [comment]
Should be fixed now
